# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Package

on:
  release:
    types: [created]
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - run: npm run build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

#new config by Ananta
  version-bump:
    needs: publish-gpr
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Bump Version
        id: bump-version
        run: echo "commit_message=$(bash .github/scripts/version_bump.sh)" >> "$GITHUB_OUTPUT"
        # env:
        #   NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}


      - name: setup git config
        run: |
          # setup the username and email.
          git config user.name "WRAPPID"
          git config user.email "wrappid.framework@gmail.com"

      - name: commit
        run: |
          # Pull, stage the file, commit and push
          git pull
          git add package.json package/package.json
          git commit -m "${{steps.bump-version.outputs.commit_message}}"
          git push origin main